# Generated by Django 5.0.2 on 2024-02-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_atendimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
